import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "var(--color-on-tertiary-container, #5b2e29)",
        "surface-dim": "var(--color-surface-dim, #d9dad8)",
        "secondary": "var(--color-secondary, #7d562d)",
        "tertiary-container": "var(--color-tertiary-container, #d4958e)",
        "surface-container": "var(--color-surface-container, #edeeeb)",
        "error": "var(--color-error, #ba1a1a)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffdad6)",
        "inverse-primary": "var(--color-inverse-primary, #9ed1bd)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "surface-container-highest": "var(--color-surface-container-highest, #e2e3e0)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "on-surface-variant": "var(--color-on-surface-variant, #404945)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #693a35)",
        "background": "var(--color-background, #f9faf7)",
        "on-primary-container": "var(--color-on-primary-container, #0e4334)",
        "tertiary": "var(--color-tertiary, #84504b)",
        "on-secondary-container": "var(--color-on-secondary-container, #7a532a)",
        "outline-variant": "var(--color-outline-variant, #c0c9c3)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #1d4f40)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #2c1600)",
        "secondary-fixed": "var(--color-secondary-fixed, #ffdcbd)",
        "surface": "var(--color-surface, #f9faf7)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #f0bd8b)",
        "on-surface": "var(--color-on-surface, #191c1b)",
        "primary-container": "var(--color-primary-container, #7daf9c)",
        "surface-tint": "var(--color-surface-tint, #376757)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #34100d)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #f9b6ae)",
        "surface-container-high": "var(--color-surface-container-high, #e7e8e6)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f0f1ee)",
        "surface-container-low": "var(--color-surface-container-low, #f3f4f1)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #9ed1bd)",
        "outline": "var(--color-outline, #707974)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "primary-fixed": "var(--color-primary-fixed, #baeed9)",
        "surface-bright": "var(--color-surface-bright, #f9faf7)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #623f18)",
        "on-error": "var(--color-on-error, #ffffff)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "on-background": "var(--color-on-background, #191c1b)",
        "surface-variant": "var(--color-surface-variant, #e2e3e0)",
        "primary": "var(--color-primary, #376757)",
        "inverse-surface": "var(--color-inverse-surface, #2e312f)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #002117)",
        "secondary-container": "var(--color-secondary-container, #ffca98)",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      spacing: {
        "max-width": "1720px",
        "gutter": "24px",
        "unit": "8px",
        "container-padding": "32px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "body-lg": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "title-md": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "display-lg": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "body-sm": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "label-md": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        "sans": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
