import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#5b2e29",
        "surface-dim": "#d9dad8",
        "secondary": "#7d562d",
        "tertiary-container": "#d4958e",
        "surface-container": "#edeeeb",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdad6",
        "inverse-primary": "#9ed1bd",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e3e0",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#404945",
        "on-tertiary-fixed-variant": "#693a35",
        "background": "#f9faf7",
        "on-primary-container": "#0e4334",
        "tertiary": "#84504b",
        "on-secondary-container": "#7a532a",
        "outline-variant": "#c0c9c3",
        "on-primary-fixed-variant": "#1d4f40",
        "on-secondary-fixed": "#2c1600",
        "secondary-fixed": "#ffdcbd",
        "surface": "#f9faf7",
        "secondary-fixed-dim": "#f0bd8b",
        "on-surface": "#191c1b",
        "primary-container": "#7daf9c",
        "surface-tint": "#376757",
        "on-tertiary-fixed": "#34100d",
        "tertiary-fixed-dim": "#f9b6ae",
        "surface-container-high": "#e7e8e6",
        "inverse-on-surface": "#f0f1ee",
        "surface-container-low": "#f3f4f1",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#9ed1bd",
        "outline": "#707974",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#baeed9",
        "surface-bright": "#f9faf7",
        "on-secondary-fixed-variant": "#623f18",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-background": "#191c1b",
        "surface-variant": "#e2e3e0",
        "primary": "#376757",
        "inverse-surface": "#2e312f",
        "on-primary-fixed": "#002117",
        "secondary-container": "#ffca98",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      spacing: {
        "max-width": "1720px",
        "gutter": "24px",
        "unit": "8px",
        "container-padding": "32px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
